### ISSUE TITLE
[QUESTION] Not Really An Issue But....

### ISSUE THREAD

**Issue by Mubashir78** [deffcolony/HP-Witchcraft-and-Wizardry#26]
This was the only way. Can I get in touch with Cheejins? And if you're reading this Cheejins, Check your inbox at Teardownmods for my Discord username. I need to tell you something.

Have a nice day!

**Comment by Mubashir78** [comment]
I'm sorry I put up an unnecessary issue which is not even an issue, but I really need to have a talk with Cheejins as I've been trying to get back to him for the last +6 months or so.

**Comment by AlexVeeBee** [comment]
message forwarded

**Comment by Mubashir78** [comment]
I Appreciate that a lot.
